version: '3.8'


services:

  app:
    image: ${DOCKER_REGISTRY-}app
    build:
      context: .
      dockerfile: App/Dockerfile
    ports:
        - "80:8080"
        - "81:8081"
    network_mode: "bridge"

