@App_HostAddress = http://localhost:80



GET {{App_HostAddress}}


###

GET {{App_HostAddress}}/todo/6

###

POST {{App_HostAddress}}/todo
Content-Type: application/json
{
  "Name": "name 11",
  "IsComplete": false
}

###
